### ISSUE TITLE
Nodemon keeps complaining about port in use after a reload

### ISSUE THREAD

**Issue by mzogheib** [mzogheib/quoll#4]
This seems to only happen in this project. Have recreated a simpler version of this project with the exact same structure and it's not an issue there. No idea why.

Observations:

- It was happening on every _second_ reload, i.e. save a file -> ok, save again -> error
- `const server = app.listen(app.get('port'), () => {})` in server.js appears to be the culprit. Commenting this out stops the issue altogether. Perhaps it's unable to properly close the server?
- For a while adding `nodemon --delay 1 server.js` was helping but not anymore
- Handling termination and interrupt signals through graceful shutdown seems to help. But it comes up every now and then.
- This looks related https://github.com/remy/nodemon/issues/1247

```[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE :::3001
[0]     at Object._errnoException (util.js:1024:11)
[0]     at _exceptionWithHostPort (util.js:1046:20)
[0]     at Server.setupListenHandle [as _listen2] (net.js:1351:14)
[0]     at listenInCluster (net.js:1392:12)
[0]     at Server.listen (net.js:1476:7)
[0]     at Function.listen (/Users/marwan/Documents/dev/#projects/quoll/node_modules/express/lib/application.js:618:24)
[0]     at Object.<anonymous> (/Users/marwan/Documents/dev/#projects/quoll/packages/server/server.js:16:20)
[0]     at Module._compile (module.js:635:30)
[0]     at Object.Module._extensions..js (module.js:646:10)
[0]     at Module.load (module.js:554:32)```

**Comment by mzogheib** [comment]
Upgrading nodemon to v2 seems to resolve this.

**Comment by mzogheib** [comment]
No longer an issue
